// Categorie di segnalazione e dati demo (condivisi con il backend/seed).
export const CATEGORIES = [
  { id: 'strade', label: 'Strade e marciapiedi', icon: '🛣️', office: 'Manutenzioni', subs: ['Buca stradale', 'Marciapiede dissestato', 'Tombino / caditoia', 'Cantiere non segnalato'] },
  { id: 'pulizia', label: 'Rifiuti e pulizia', icon: '🧹', office: 'Ambiente', subs: ['Rifiuti abbandonati', 'Cestino stracolmo', 'Discarica abusiva', 'Spazzamento strade'] },
  { id: 'illuminazione', label: 'Illuminazione pubblica', icon: '💡', office: 'Manutenzioni', subs: ['Lampione spento', 'Lampione sempre acceso', 'Palo danneggiato'] },
  { id: 'verde', label: 'Verde pubblico', icon: '🌳', office: 'Ambiente', subs: ['Albero pericolante', 'Sfalcio erba', 'Area gioco danneggiata', 'Parco da manutenere'] },
  { id: 'arredo', label: 'Arredo urbano', icon: '🚏', office: 'Manutenzioni', subs: ['Panchina rotta', 'Fermata bus', 'Fontanella', 'Segnaletica turistica'] },
  { id: 'segnaletica', label: 'Segnaletica stradale', icon: '🚸', office: 'Polizia Municipale', subs: ['Segnale mancante', 'Segnale danneggiato', 'Strisce pedonali sbiadite'] },
  { id: 'veicoli', label: 'Veicoli abbandonati', icon: '🚗', office: 'Polizia Municipale', subs: ['Auto abbandonata', 'Relitto', 'Sosta pericolosa'] },
  { id: 'cimiteri', label: 'Cimiteri', icon: '🕯️', office: 'Servizi cimiteriali', subs: ['Manutenzione loculi', 'Pulizia aree', 'Illuminazione votiva'] },
  { id: 'acqua', label: 'Acqua e fognature', icon: '💧', office: 'Ambiente', subs: ['Perdita idrica', 'Tombino otturato', 'Allagamento'] }
];

export const OFFICE_BY_CATEGORY = Object.fromEntries(CATEGORIES.map((c) => [c.label, c.office]));

export const DEFAULT_REPORTS = [
  { id: 'FARO-2026-001', ownerId: null, name: 'Maria Licata', email: 'maria.licata@example.it', category: 'Strade e marciapiedi', subcategory: 'Buca stradale', address: 'Corso Umberto I, 42', lat: 37.3639, lng: 13.8496, description: 'Buca pericolosa vicino alle strisce pedonali, serve messa in sicurezza urgente.', priority: 'Alta', status: 'In lavorazione', office: 'Manutenzioni', createdAt: '2026-07-12T09:00:00.000Z', attachmentName: 'buca.jpg', history: [{ status: 'Ricevuta', note: 'Segnalazione acquisita dal portale.', at: '2026-07-12T09:00:00.000Z' }, { status: 'In lavorazione', note: 'Presa in carico da Manutenzioni.', at: '2026-07-13T08:00:00.000Z' }] },
  { id: 'FARO-2026-002', ownerId: null, name: 'Giuseppe Alaimo', email: 'g.alaimo@example.it', category: 'Illuminazione pubblica', subcategory: 'Lampione spento', address: 'Via Nazionale, 8', lat: 37.3701, lng: 13.8455, description: 'Tre lampioni consecutivi spenti da una settimana, strada al buio la sera.', priority: 'Ordinaria', status: 'Ricevuta', office: 'Manutenzioni', createdAt: '2026-07-13T20:30:00.000Z', attachmentName: '', history: [{ status: 'Ricevuta', note: 'Segnalazione acquisita dal portale.', at: '2026-07-13T20:30:00.000Z' }] },
  { id: 'FARO-2026-003', ownerId: null, name: 'Rosa Cammarata', email: 'rosa.cammarata@example.it', category: 'Rifiuti e pulizia', subcategory: 'Discarica abusiva', address: 'Contrada Giarre', lat: 37.3555, lng: 13.8600, description: 'Cumulo di rifiuti ingombranti abbandonati ai margini della strada.', priority: 'Urgente', status: 'Risolta', office: 'Ambiente', createdAt: '2026-07-08T07:15:00.000Z', attachmentName: 'rifiuti.jpg', history: [{ status: 'Ricevuta', note: 'Segnalazione acquisita dal portale.', at: '2026-07-08T07:15:00.000Z' }, { status: 'Risolta', note: 'Area bonificata.', at: '2026-07-10T11:00:00.000Z' }] },
  { id: 'FARO-2026-004', ownerId: null, name: 'Antonino Vella', email: 'a.vella@example.it', category: 'Verde pubblico', subcategory: 'Albero pericolante', address: 'Villa Comunale', lat: 37.3660, lng: 13.8510, description: 'Ramo spezzato pendente sopra il vialetto pedonale, rischio caduta.', priority: 'Alta', status: 'In lavorazione', office: 'Ambiente', createdAt: '2026-07-14T10:20:00.000Z', attachmentName: 'ramo.jpg', history: [{ status: 'Ricevuta', note: 'Segnalazione acquisita dal portale.', at: '2026-07-14T10:20:00.000Z' }, { status: 'In lavorazione', note: 'Sopralluogo programmato.', at: '2026-07-15T09:00:00.000Z' }] },
  { id: 'FARO-2026-005', ownerId: null, name: 'Carmela Dulcimascolo', email: 'c.d@example.it', category: 'Segnaletica stradale', subcategory: 'Strisce pedonali sbiadite', address: 'Via Carlo Alberto', lat: 37.3648, lng: 13.8489, description: 'Attraversamento pedonale davanti alla scuola quasi invisibile.', priority: 'Ordinaria', status: 'Ricevuta', office: 'Polizia Municipale', createdAt: '2026-07-15T07:45:00.000Z', attachmentName: '', history: [{ status: 'Ricevuta', note: 'Segnalazione acquisita dal portale.', at: '2026-07-15T07:45:00.000Z' }] },
  { id: 'FARO-2026-006', ownerId: null, name: 'Salvatore Grech', email: 's.grech@example.it', category: 'Veicoli abbandonati', subcategory: 'Auto abbandonata', address: 'Via Puccini', lat: 37.3689, lng: 13.8532, description: 'Auto senza targa ferma da mesi, occupa un parcheggio e raccoglie rifiuti.', priority: 'Ordinaria', status: 'In lavorazione', office: 'Polizia Municipale', createdAt: '2026-07-11T16:00:00.000Z', attachmentName: 'auto.jpg', history: [{ status: 'Ricevuta', note: 'Segnalazione acquisita dal portale.', at: '2026-07-11T16:00:00.000Z' }, { status: 'In lavorazione', note: 'Verifica proprietà in corso.', at: '2026-07-13T10:00:00.000Z' }] },
  { id: 'FARO-2026-007', ownerId: null, name: 'Lucia Sardo', email: 'l.sardo@example.it', category: 'Acqua e fognature', subcategory: 'Perdita idrica', address: 'Via Cavour, 15', lat: 37.3625, lng: 13.8471, description: 'Perdita d\'acqua dal marciapiede, spreco continuo da giorni.', priority: 'Alta', status: 'Risolta', office: 'Ambiente', createdAt: '2026-07-06T08:30:00.000Z', attachmentName: '', history: [{ status: 'Ricevuta', note: 'Segnalazione acquisita dal portale.', at: '2026-07-06T08:30:00.000Z' }, { status: 'In lavorazione', note: 'Squadra inviata.', at: '2026-07-07T09:00:00.000Z' }, { status: 'Risolta', note: 'Perdita riparata.', at: '2026-07-09T14:00:00.000Z' }] },
  { id: 'FARO-2026-008', ownerId: null, name: 'Giovanni Bruccoleri', email: 'g.brucc@example.it', category: 'Arredo urbano', subcategory: 'Panchina rotta', address: 'Piazza IV Novembre', lat: 37.3652, lng: 13.8503, description: 'Panchina con assi rotte, pericolosa per gli anziani che sostano in piazza.', priority: 'Ordinaria', status: 'Ricevuta', office: 'Manutenzioni', createdAt: '2026-07-15T18:10:00.000Z', attachmentName: 'panchina.jpg', history: [{ status: 'Ricevuta', note: 'Segnalazione acquisita dal portale.', at: '2026-07-15T18:10:00.000Z' }] }
];
